### ISSUE TITLE
CustomPortfolio_Expr.prj gives an error when opened in MATLAB or experimentManager

### ISSUE THREAD

**Issue by cerkut** [mathworks/managing_asset_allocation_with_experiment_manager#1]
The error is:

Unable to load project at <local_folder>
Unable to find a definition folder for the project in resources/project.

I could create an empty project, then include the mat files and mlx file in the project, and report. But much better if this would work out of the box.

**Comment by saragalante** [comment]
Hi cerkut,

Thanks for bringing this up! I believe I've fixed the problem - you should have no issue with using the repo as is now (project file included). Feel free to reach out if you have additional questions.

Thanks,
Sara
